on:
  push:
    tags:
      - "v*" # Triggers when a version tag (eg: v1.0.0) is pushed.
name: 🚀 Deploy website on tag push to OVH FTP
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Yarn
        run: corepack enable && corepack prepare yarn@stable --activate

      - name: 🔨 Build Project
        run: |
          yarn
          yarn build --configuration production

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
          server-dir: /www/
